name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.0.0, v2.1.3, etc.

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linting
      run: npm run lint
    
    - name: Compile TypeScript
      run: npm run compile
    
    - name: Run tests
      run: npm test
      continue-on-error: true  # Remove this when you add actual tests
    
    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
    
    - name: Update package.json version
      run: |
        npm version ${{ steps.get_version.outputs.VERSION }} --no-git-tag-version
    
    - name: Package extension
      run: |
        npm install -g vsce
        vsce package
    
    - name: Get package filename
      id: get_package
      run: |
        PACKAGE_FILE=$(ls *.vsix)
        echo "PACKAGE_FILE=${PACKAGE_FILE}" >> $GITHUB_OUTPUT
    
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ steps.get_version.outputs.VERSION }}
        body: |
          ## Changes in this Release
          
          Please see the [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) for details.
          
          ## Installation
          
          ### From VS Code Marketplace
          Search for "Function Folding" in the VS Code Extensions marketplace.
          
          ### Manual Installation
          ```bash
          code --install-extension ${{ steps.get_package.outputs.PACKAGE_FILE }}
          ```
          
          ## What's New
          - Check the changelog for detailed information about new features and fixes
          
          ---
          
          **Full Changelog**: https://github.com/${{ github.repository }}/compare/v${{ steps.get_version.outputs.VERSION }}...v${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false
    
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./${{ steps.get_package.outputs.PACKAGE_FILE }}
        asset_name: ${{ steps.get_package.outputs.PACKAGE_FILE }}
        asset_content_type: application/zip
    
    - name: Publish to VS Code Marketplace
      run: |
        vsce publish -p ${{ secrets.VSCE_PAT }}
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
      continue-on-error: true  # Don't fail the release if marketplace publish fails
    
    - name: Publish to Open VSX Registry
      run: |
        npm install -g ovsx
        ovsx publish ${{ steps.get_package.outputs.PACKAGE_FILE }} -p ${{ secrets.OVSX_PAT }}
      env:
        OVSX_PAT: ${{ secrets.OVSX_PAT }}
      continue-on-error: true  # Don't fail the release if Open VSX publish fails
